services:
  fastapi:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
