NONE_ACCOUNT = "기타"
REDIS_RICH_PICK_KEY = "richpick"
REDIS_RICH_PICK_NAME_KEY = "richpickname"
RICH_PICK_SECOND = 60 * 60

REDIS_RICH_PORTFOLIO_KEY = "richportfolio"
REDIS_RICH_PORTFOLIO_SECOND = 60 * 60 * 24

DEFAULT_TIP = "자신이 사랑하는 일을 찾아 투자하세요."
PAST_MONTH_DAY = 31
FULL_PERCENTAGE_RATE = 100.0
TIP_EXPIRE_SECOND = 60 * 60 * (24 + 1)

PORTFOLIO_SHARE_LIMIT = 8
