"""is_deleted 컬럼 추가

Revision ID: 07eda1fe2792
Revises: 38aa17355450
Create Date: 2025-01-08 11:14:31.234647

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07eda1fe2792"
down_revision: Union[str, None] = "38aa17355450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("asset_field", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("asset_stock", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("dividend", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("invest_tip", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("market_index_daily", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("market_index_daily", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("market_index_daily", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("market_index_daily", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.drop_index("idx_name_date_desc", table_name="market_index_daily")
    op.create_index("idx_name_date_desc", "market_index_daily", ["name", sa.text("date DESC")], unique=False)
    op.add_column("market_index_minutely", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("market_index_minutely", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("market_index_minutely", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("market_index_minutely", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.drop_index("idx_name_datetime", table_name="market_index_minutely")
    op.create_index("idx_name_datetime", "market_index_minutely", ["name", sa.text("datetime DESC")], unique=False)
    op.add_column("stock", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("stock_daily", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("stock_daily", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("stock_daily", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("stock_daily", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.drop_index("idx_code_date", table_name="stock_daily")
    op.create_index("idx_code_date", "stock_daily", ["code", sa.text("date DESC")], unique=False)
    op.add_column("stock_minutely", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("stock_minutely", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("stock_minutely", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("stock_minutely", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.drop_index("idx_code_datetime_desc", table_name="stock_minutely")
    op.create_index("idx_code_datetime_desc", "stock_minutely", ["code", sa.text("datetime DESC")], unique=False)
    op.add_column("user", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_deleted")
    op.drop_index("idx_code_datetime_desc", table_name="stock_minutely")
    op.create_index("idx_code_datetime_desc", "stock_minutely", ["code", "datetime"], unique=False)
    op.drop_column("stock_minutely", "is_deleted")
    op.drop_column("stock_minutely", "deleted_at")
    op.drop_column("stock_minutely", "updated_at")
    op.drop_column("stock_minutely", "created_at")
    op.drop_index("idx_code_date", table_name="stock_daily")
    op.create_index("idx_code_date", "stock_daily", ["code", "date"], unique=False)
    op.drop_column("stock_daily", "is_deleted")
    op.drop_column("stock_daily", "deleted_at")
    op.drop_column("stock_daily", "updated_at")
    op.drop_column("stock_daily", "created_at")
    op.drop_column("stock", "is_deleted")
    op.drop_index("idx_name_datetime", table_name="market_index_minutely")
    op.create_index("idx_name_datetime", "market_index_minutely", ["name", "datetime"], unique=False)
    op.drop_column("market_index_minutely", "is_deleted")
    op.drop_column("market_index_minutely", "deleted_at")
    op.drop_column("market_index_minutely", "updated_at")
    op.drop_column("market_index_minutely", "created_at")
    op.drop_index("idx_name_date_desc", table_name="market_index_daily")
    op.create_index("idx_name_date_desc", "market_index_daily", ["name", "date"], unique=False)
    op.drop_column("market_index_daily", "is_deleted")
    op.drop_column("market_index_daily", "deleted_at")
    op.drop_column("market_index_daily", "updated_at")
    op.drop_column("market_index_daily", "created_at")
    op.drop_column("invest_tip", "is_deleted")
    op.drop_column("dividend", "is_deleted")
    op.drop_column("asset_stock", "is_deleted")
    op.drop_column("asset_field", "is_deleted")
    op.drop_column("asset", "is_deleted")
    # ### end Alembic commands ###
